---
title: "multilevel smokers art gallery analyses"
author: "Monica Thieu"
date: "1/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(magrittr)
options(mc.cores = parallel::detectCores())

demos = read_csv("ignore/demographics/demo_smoke_habits.csv") %>%
  mutate(cigs_per_day_est = 10 * cigs_per_day_est) %>%
  mutate_if(is.numeric, as.integer) %>%
  mutate(cigs_per_day_est = .1 * cigs_per_day_est,
         ppm_on = if_else(condition == 1, ppm_s1, ppm_s2),
         ppm_off = if_else(condition == 1, ppm_s2, ppm_s1))

raw = tibble(filename = list.files("ignore/data_raw", pattern = ".txt", full.names = TRUE)) %>%
  mutate(data = map(filename, ~.x %>%
                      read_delim(delim = "\t",
                                 skip = 9,
                                 col_names = FALSE) %>%
                      select(trial = X1,
                             stimOnsetTime = X2,
                             exptCond = X4,
                             stimNum = X6,
                             cue = X7,
                             probe = X8,
                             valid = X9,
                             resp = X10,
                             corResp = X11,
                             acc = X12,
                             rt = X13) %>%
                      mutate_at(c("trial", "exptCond", "valid", "resp", "corResp", "acc"),
                                as.integer) %>%
                    mutate_at(c("cue", "probe"), ~recode(., `1` = "art", `2` = "room")))) %>%
  mutate(subj_num = as.integer(str_sub(filename, start = 32L, end = 34L)),
         session_num = str_sub(filename, start = -5L, end = -5L),
         session_num = if_else(session_num == "2", 2L, 1L)) %>%
  select(-filename) %>%
  left_join(demos %>%
              select(subj_num, condition, ppm_on, ppm_off) %>%
              pivot_longer(names_to = "on_smoking", values_to = "ppm", cols = starts_with("ppm")) %>% 
              mutate(on_smoking = recode(on_smoking, ppm_on = 1L, ppm_off = 0L),
                     ppm_z = c(scale(ppm))),
            by = "subj_num") %>%
  # Scrub all subjects who don't appear in demographics data
  filter(!is.na(condition)) %>%
  mutate(on_smoking = as.integer(session_num == condition)) %>%
  unnest(data)
```

## checking data quality

```{r}
# Should be 0 length
raw %>%
  count(subj_num, on_smoking) %>%
  filter(n < 80)
```

For eyeballing:

```{r}
raw %>%
  group_by(subj_num, on_smoking, corResp) %>%
  summarize(mean_acc = mean(acc)) %>%
  pivot_wider(names_from = corResp, values_from = mean_acc, names_prefix = "rate_") %>%
  rename(rate_cr = rate_0, rate_hit = rate_1) %>%
  mutate(rate_fa = 1 - rate_cr) %>%
  ggplot(aes(x = rate_hit, y = rate_fa, color = factor(on_smoking))) +
  geom_point()
```



## results baby

```{r}
model <- lme4::glmer(resp ~ corResp * probe * on_smoking + (1 + corResp | subj_num),
                     data = raw %>% filter(valid == 1),
                     family = binomial(link = "logit"))
```

```{r}
summary(model)
```

```{r, eval = FALSE}
models <- tibble(name = c("onoff", "ppm", "control", "relational"),
                 has_exptCond = list(0:1, 1L, 0L, 1L),
                 has_smoking = c("on_smoking", "ppm_z", "on_smoking", "on_smoking")) %>%
  mutate(data = map(has_exptCond, ~raw %>%
                      filter(valid == 1, exptCond %in% .x)),
         terms = map_if(has_exptCond, lengths(has_exptCond) > 1,
                        ~c("corResp", "probe", "exptCond"),
                        .else = ~c("corResp", "probe")),
         terms = map2(terms, has_smoking, ~c(.x, .y)),
         txt_formula = map_chr(terms, ~paste(.x, collapse = " + ")),
         txt_formula = paste0("resp ~ (", txt_formula, ")^3 + (1 + corResp | subj_num)"),
         model = map2(txt_formula, data, ~rstanarm::stan_glmer(as.formula(.x),
                                                               family = binomial(link = "logit"),
                                                               data = .y,
                                                               prior = rstanarm::cauchy(0, 5),
                                                               prior_intercept = rstanarm::cauchy(0, 5))))

save(models, file = "ignore/data_R/models_rstanarm.rda")
```

```{r}
load("ignore/data_R/models_rstanarm.rda")
```

```{r}
preplots <- models %>%
  select(name, model) %>%
  mutate(model = map(model, ~.x %>%
                       as.data.frame() %>%
                       as_tibble() %>%
                       mutate(iteration = 1:nrow(.)) %>%
                       select(-contains("["), -contains("sigma")) %>%
                       rename(intercept = "(Intercept)") %>%
                       pivot_longer(cols = -iteration, names_to = "term", values_to = "estimate")))
```

```{r}
preplots$model[[1]] %>%
  ggplot(aes(x = estimate)) +
  geom_histogram() +
  geom_vline(xintercept = 0, linetype = 3) +
  facet_wrap(~ term, scales = "free_x")
```


```{r}
preplots_fixef <- models %>%
  select(name, terms, data, model) %>%
  mutate(data = map2(data, terms, ~.x %>% select(.y) %>% distinct()),
         predicted = map2(model, data, ~.x %>%
                            rstanarm::posterior_linpred(transform = TRUE,
                                                        newdata = .y,
                                                        re.form = NA,
                                                        draws = 1000)),
         # Must expand AFTER predictions is already done to repeat for iterations
         data = map(data, ~.x %>%
                      mutate(obs = 1:nrow(.),
                             iteration = map(obs, ~1:1000)) %>%
                      unchop(iteration)),
         predicted = map(predicted, ~.x %>%
                           as_tibble() %>%
                           mutate(iteration = 1:nrow(.)) %>%
                           pivot_longer(cols = -iteration, names_to = "obs", values_to = "resp_pred") %>%
                           mutate(obs = as.integer(obs))),
         predicted = map2(data, predicted, ~left_join(.x, .y, by = c("obs", "iteration")))) %>%
  select(name, predicted)
```

```{r}
preplots_fixef$predicted[[1]] %>%
  select(-obs) %>%
  mutate(corResp = recode(corResp, `0` = "fa", `1` = "hit")) %>%
  pivot_wider(names_from = corResp, values_from = resp_pred, names_prefix = "rate_") %>%
  mutate(dprime = qnorm(rate_hit) - qnorm(rate_fa)) %>%
  ggplot(aes(x = probe, y = dprime, color = factor(exptCond))) +
  geom_jitter(alpha = 0.3) +
  facet_grid(~ on_smoking)
```

```{r}
preplots_fixef$predicted[[1]] %>%
  select(-obs) %>%
  mutate(corResp = recode(corResp, `0` = "fa", `1` = "hit")) %>%
  pivot_wider(names_from = corResp, values_from = resp_pred, names_prefix = "rate_") %>%
  mutate(dprime = qnorm(rate_hit) - qnorm(rate_fa)) %>%
  ggplot(aes(x = probe, y = dprime, color = factor(exptCond))) +
  geom_jitter(alpha = 0.3) +
  facet_grid(~ on_smoking)
```
